#!/bin/bash
#
# Perform necessary fpm setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}


echo "Thank you for installing fpm!"
echo "If you want to build RPMs you'll"
echo "probably need to run: "
echo "yum -y install gcc rpm-build make"
exit 0
